// <auto-generated />
using System;
using LifeLedger.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeLedger.Api.Data.Migrations
{
    [DbContext(typeof(LifeLedgerDbContext))]
    [Migration("20260716170925_AddNetWorthHistory")]
    partial class AddNetWorthHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LifeLedger.Api.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapitalGainsTaxCountryCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CapitalGainsTaxRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedAnnualReturn")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLiquid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volatility")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AssetQuoteSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "CapturedAt");

                    b.ToTable("AssetQuoteSnapshots");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.CareerPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualInsurableIncome")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedMonthlyPublicPension")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PensionAge")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("CareerPeriods");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IndexedToInflation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.FinancialScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "IsBaseline");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.IncomeStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualGrowthRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxCountryCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.InvestmentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedAnnualReturn")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyContribution")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Liability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyPayment")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutstandingBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PaidOffOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Liabilities");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.NetWorthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetWorth")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "CapturedAt");

                    b.ToTable("NetWorthSnapshots");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildrenCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedLifespan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeCountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerBirthYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.ScenarioEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("HappensOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyCashImpact")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OneOffCashImpact")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("RecurrenceEndsOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecurrenceFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.SimulationAssumptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultReturnVolatility")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InflationRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("MonteCarloRuns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetirementAge")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SafeWithdrawalRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaryGrowthRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId")
                        .IsUnique();

                    b.ToTable("Assumptions");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Asset", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("Assets")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AssetQuoteSnapshot", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.CareerPeriod", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Profile", "Profile")
                        .WithMany("Careers")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Expense", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("Expenses")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.FinancialScenario", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.IncomeStream", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("Incomes")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.InvestmentPlan", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("Investments")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Liability", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("Liabilities")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.NetWorthSnapshot", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Profile", "Profile")
                        .WithMany("NetWorthSnapshots")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.ScenarioEvent", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("Events")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.SimulationAssumptions", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithOne("Assumptions")
                        .HasForeignKey("LifeLedger.Api.Domain.SimulationAssumptions", "ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.FinancialScenario", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Assumptions")
                        .IsRequired();

                    b.Navigation("Events");

                    b.Navigation("Expenses");

                    b.Navigation("Incomes");

                    b.Navigation("Investments");

                    b.Navigation("Liabilities");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Profile", b =>
                {
                    b.Navigation("Careers");

                    b.Navigation("NetWorthSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
