// <auto-generated />
using System;
using LifeLedger.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeLedger.Api.Data.Migrations
{
    [DbContext(typeof(LifeLedgerDbContext))]
    partial class LifeLedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LifeLedger.Api.Data.ApplicationSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AllocationStrategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId", "EffectiveFrom");

                    b.ToTable("AllocationStrategies");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AllocationStrategyTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AllocationStrategyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TolerancePercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllocationStrategyId", "Category")
                        .IsUnique();

                    b.ToTable("AllocationStrategyTargets");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AcquisitionCosts")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapitalGainsTaxCountryCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CapitalGainsTaxRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomCategory")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedAnnualReturn")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalProvider")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncludedInPortfolioAllocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLiquid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PurchasedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValuationSource")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValuedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volatility")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId", "ExternalProvider", "ExternalId")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AssetCharacteristicProfile", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssetId");

                    b.ToTable("AssetCharacteristicProfiles");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AssetLiabilityLink", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LiabilityId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AllocationRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("AssetId", "LiabilityId");

                    b.HasIndex("LiabilityId");

                    b.ToTable("AssetLiabilityLinks");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AssetQuoteSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "CapturedAt");

                    b.ToTable("AssetQuoteSnapshots");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AssetValuationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValuedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "ValuedOn")
                        .IsUnique();

                    b.ToTable("AssetValuationSnapshots");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifierHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LinkedAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaskedIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkedAssetId");

                    b.HasIndex("ScenarioId", "IdentifierHash")
                        .IsUnique();

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.BankStatementImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImporterKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PeriodEndsOn")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PeriodStartsOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId", "SourceFingerprint")
                        .IsUnique();

                    b.ToTable("BankStatementImports");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BalanceAfter")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BankStatementImportId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BookedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Classification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Counterparty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExcludedFromSpendingAnalysis")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LinkedAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LinkedInvestmentPlanId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValueOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkedAssetId");

                    b.HasIndex("LinkedInvestmentPlanId");

                    b.HasIndex("BankStatementImportId", "Fingerprint")
                        .IsUnique();

                    b.ToTable("BankTransactions");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.CareerPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualInsurableIncome")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedMonthlyPublicPension")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PensionAge")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("CareerPeriods");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IndexedToInflation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LinkedAssetId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedBankCategory")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SaveInAdvance")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("SavingsStartsOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkedAssetId");

                    b.HasIndex("ScenarioId", "ObservedBankCategory", "Currency");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.ExpenseAmountChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId", "EffectiveOn")
                        .IsUnique();

                    b.ToTable("ExpenseAmountChanges");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.FinancialScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "IsBaseline");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.IncomeMonthlyAllocation", b =>
                {
                    b.Property<Guid>("IncomeStreamId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Share")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("IncomeStreamId", "Month");

                    b.ToTable("IncomeMonthlyAllocations");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.IncomeStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AmountMode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualGrowthRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LinkedAssetId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxCountryCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkedAssetId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.InvestmentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedAnnualReturn")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyContribution")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Liability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyPayment")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutstandingBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PaidOffOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Liabilities");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.NetWorthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetWorth")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "CapturedAt");

                    b.ToTable("NetWorthSnapshots");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.PlannedAssetSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapitalGainsTaxCountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CapitalGainsTaxRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("Destination")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DestinationAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DestinationInvestmentPlanId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossSalePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("HappensOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RepayLinkedLiabilities")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SellingCosts")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseProjectedValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasIndex("DestinationAssetId");

                    b.HasIndex("DestinationInvestmentPlanId");

                    b.HasIndex("ScenarioId", "HappensOn");

                    b.ToTable("AssetSales");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildrenCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedLifespan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeCountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerBirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.ScenarioEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("HappensOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyCashImpact")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OneOffCashImpact")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("RecurrenceEndsOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecurrenceFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.SimulationAssumptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultReturnVolatility")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InflationRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("MonteCarloRuns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetirementAge")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SafeWithdrawalRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaryGrowthRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId")
                        .IsUnique();

                    b.ToTable("Assumptions");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AllocationStrategy", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("AllocationStrategies")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AllocationStrategyTarget", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.AllocationStrategy", "AllocationStrategy")
                        .WithMany("Targets")
                        .HasForeignKey("AllocationStrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllocationStrategy");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Asset", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("Assets")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AssetCharacteristicProfile", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Asset", "Asset")
                        .WithOne("CharacteristicProfile")
                        .HasForeignKey("LifeLedger.Api.Domain.AssetCharacteristicProfile", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AssetLiabilityLink", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Asset", "Asset")
                        .WithMany("LiabilityLinks")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLedger.Api.Domain.Liability", "Liability")
                        .WithMany("AssetLinks")
                        .HasForeignKey("LiabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Liability");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AssetQuoteSnapshot", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AssetValuationSnapshot", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Asset", "Asset")
                        .WithMany("ValuationSnapshots")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.BankAccount", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Asset", "LinkedAsset")
                        .WithMany()
                        .HasForeignKey("LinkedAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("BankAccounts")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedAsset");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.BankStatementImport", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.BankAccount", "BankAccount")
                        .WithMany("Imports")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.BankTransaction", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.BankStatementImport", "BankStatementImport")
                        .WithMany("Transactions")
                        .HasForeignKey("BankStatementImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLedger.Api.Domain.Asset", "LinkedAsset")
                        .WithMany()
                        .HasForeignKey("LinkedAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LifeLedger.Api.Domain.InvestmentPlan", "LinkedInvestmentPlan")
                        .WithMany()
                        .HasForeignKey("LinkedInvestmentPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BankStatementImport");

                    b.Navigation("LinkedAsset");

                    b.Navigation("LinkedInvestmentPlan");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.CareerPeriod", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Profile", "Profile")
                        .WithMany("Careers")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Expense", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Asset", "LinkedAsset")
                        .WithMany()
                        .HasForeignKey("LinkedAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("Expenses")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedAsset");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.ExpenseAmountChange", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Expense", "Expense")
                        .WithMany("AmountChanges")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.FinancialScenario", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.IncomeMonthlyAllocation", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.IncomeStream", "IncomeStream")
                        .WithMany("MonthlyAllocations")
                        .HasForeignKey("IncomeStreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeStream");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.IncomeStream", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Asset", "LinkedAsset")
                        .WithMany()
                        .HasForeignKey("LinkedAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("Incomes")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedAsset");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.InvestmentPlan", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("Investments")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Liability", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("Liabilities")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.NetWorthSnapshot", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Profile", "Profile")
                        .WithMany("NetWorthSnapshots")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.PlannedAssetSale", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLedger.Api.Domain.Asset", "DestinationAsset")
                        .WithMany()
                        .HasForeignKey("DestinationAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LifeLedger.Api.Domain.InvestmentPlan", "DestinationInvestmentPlan")
                        .WithMany()
                        .HasForeignKey("DestinationInvestmentPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("AssetSales")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("DestinationAsset");

                    b.Navigation("DestinationInvestmentPlan");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.ScenarioEvent", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithMany("Events")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.SimulationAssumptions", b =>
                {
                    b.HasOne("LifeLedger.Api.Domain.FinancialScenario", "Scenario")
                        .WithOne("Assumptions")
                        .HasForeignKey("LifeLedger.Api.Domain.SimulationAssumptions", "ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.AllocationStrategy", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Asset", b =>
                {
                    b.Navigation("CharacteristicProfile");

                    b.Navigation("LiabilityLinks");

                    b.Navigation("ValuationSnapshots");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.BankAccount", b =>
                {
                    b.Navigation("Imports");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.BankStatementImport", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Expense", b =>
                {
                    b.Navigation("AmountChanges");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.FinancialScenario", b =>
                {
                    b.Navigation("AllocationStrategies");

                    b.Navigation("AssetSales");

                    b.Navigation("Assets");

                    b.Navigation("Assumptions")
                        .IsRequired();

                    b.Navigation("BankAccounts");

                    b.Navigation("Events");

                    b.Navigation("Expenses");

                    b.Navigation("Incomes");

                    b.Navigation("Investments");

                    b.Navigation("Liabilities");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.IncomeStream", b =>
                {
                    b.Navigation("MonthlyAllocations");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Liability", b =>
                {
                    b.Navigation("AssetLinks");
                });

            modelBuilder.Entity("LifeLedger.Api.Domain.Profile", b =>
                {
                    b.Navigation("Careers");

                    b.Navigation("NetWorthSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
