namespace LifeLedger.Api.Domain;

/// <summary>Represents the person or household whose financial life is simulated.</summary>
public sealed class Profile
{
    /// <summary>Stable identifier of the profile.</summary>
    public Guid Id { get; set; } = Guid.NewGuid();
    /// <summary>Friendly name shown to the owner of the plan.</summary>
    public string DisplayName { get; set; } = "My financial life";
    /// <summary>Date of birth used to calculate age throughout projections.</summary>
    public DateOnly BirthDate { get; set; }
    /// <summary>Sex selected for life-expectancy reference values; neutral avoids a sex-specific reference.</summary>
    public ProfileSex Sex { get; set; } = ProfileSex.Neutral;
    /// <summary>ISO country code of the primary residence.</summary>
    public string HomeCountryCode { get; set; } = "PL";
    /// <summary>ISO 4217 currency used to display consolidated amounts.</summary>
    public string BaseCurrency { get; set; } = "EUR";
    /// <summary>Last age included in lifetime projections; defaults to the rounded European planning reference.</summary>
    public int ExpectedLifespan { get; set; } = 82;
    /// <summary>Optional birth year of the partner.</summary>
    public int? PartnerBirthYear { get; set; }
    /// <summary>Number of dependent children represented in the plan.</summary>
    public int ChildrenCount { get; set; }
    /// <summary>UTC timestamp at which the profile was created.</summary>
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
    /// <summary>Career periods used to estimate public pensions across countries.</summary>
    public List<CareerPeriod> Careers { get; set; } = [];
    /// <summary>Locally captured net-worth observations for the reference scenario.</summary>
    public List<NetWorthSnapshot> NetWorthSnapshots { get; set; } = [];
}

/// <summary>Represents an insured career period in one country.</summary>
public sealed class CareerPeriod
{
    /// <summary>Stable identifier of the career period.</summary>
    public Guid Id { get; set; } = Guid.NewGuid();
    /// <summary>Identifier of the owning profile.</summary>
    public Guid ProfileId { get; set; }
    /// <summary>Navigation to the owning profile.</summary>
    public Profile? Profile { get; set; }
    /// <summary>ISO country code of the pension system.</summary>
    public string CountryCode { get; set; } = "PL";
    /// <summary>First date covered by this career period.</summary>
    public DateOnly StartedOn { get; set; }
    /// <summary>Last covered date; null means the period is ongoing.</summary>
    public DateOnly? EndedOn { get; set; }
    /// <summary>Annual income eligible for public-pension calculation.</summary>
    public decimal AnnualInsurableIncome { get; set; }
    /// <summary>Estimated gross monthly public pension generated by this period.</summary>
    public decimal EstimatedMonthlyPublicPension { get; set; }
    /// <summary>Expected age at which this pension becomes available.</summary>
    public int PensionAge { get; set; } = 65;
    /// <summary>Free-form explanatory notes supplied by the user.</summary>
    public string Notes { get; set; } = string.Empty;
}

/// <summary>Stores the actual net worth observed for a profile at a point in time.</summary>
public sealed class NetWorthSnapshot
{
    /// <summary>Stable identifier of the snapshot.</summary>
    public Guid Id { get; set; } = Guid.NewGuid();
    /// <summary>Identifier of the profile whose wealth was captured.</summary>
    public Guid ProfileId { get; set; }
    /// <summary>Navigation to the owning profile.</summary>
    public Profile? Profile { get; set; }
    /// <summary>UTC timestamp at which the local server captured the value.</summary>
    public DateTimeOffset CapturedAt { get; set; } = DateTimeOffset.UtcNow;
    /// <summary>Assets minus liabilities in <see cref="Currency"/>.</summary>
    public decimal NetWorth { get; set; }
    /// <summary>ISO 4217 currency used to consolidate the snapshot.</summary>
    public string Currency { get; set; } = "EUR";
}
